Главная страница
htmlacademy-htmlcss/2313423-sedona-36 pull request #3
Opened 2023-01-25 14:11 UTC by soulmonova

Код на проверку

2023-01-27 06:53 UTC, summertime-fms requested changes

2023-01-27 06:53 UTC, summertime-fms commented on hotels.html
> +          <li class="navigation item"><a class="navigation-link current" href="hotels.html">Гостиницы</a>
Тире в классе пропустила

2023-01-27 06:53 UTC, summertime-fms commented on hotels.html
> +          <li class="navigation item"><a class="navigation-link current" href="hotels.html">Гостиницы</a>
И давай ссылки внутри li на новую строчку перенесём

2023-01-27 06:53 UTC, summertime-fms commented on hotels.html
> +      <img class="page-header-logo" alt="Логотип города Седона" src=""</a>
Закрывающий `a` на новую строку

2023-01-27 06:53 UTC, summertime-fms commented on hotels.html
> +<nav class="navigation-user">
Можно не разбивать на две навигации, можно все в одну сложить. Либо один список который выше в nav, а второй просто оставить рядом.

2023-01-27 06:53 UTC, summertime-fms commented on hotels.html
> +Избранное
Съехало) Нужен отступ

2023-01-27 06:53 UTC, summertime-fms commented on hotels.html
> +    <li class="navigation item">
Вновь тире пропустила. И в принципе эти же пункты не похожи не пункты перого списка, так что класс скорее всего другой нужен будет.

2023-01-27 06:53 UTC, summertime-fms commented on hotels.html
> +  <main class="main-inner"
Для этого тега вряд ли понадобится класс, довольно редкий случай.

2023-01-27 06:53 UTC, summertime-fms commented on hotels.html
> +    <legend class="hotels-filter-title" type="checkbox">Инфраструктура:</legend>
У легенды не может быть type, это у инпутов только.

2023-01-27 06:53 UTC, summertime-fms commented on hotels.html
> +      <legend class="hotels-filtr-title" type="radio">Тип Жилья:</legend>
Аналогично выше.

2023-01-27 06:53 UTC, summertime-fms commented on hotels.html
> +<a href="#" class="button button-light">
А давай эти 3 кнопки сгруппируев в див, они же все таки особняком стоят в макете.

2023-01-27 06:53 UTC, summertime-fms commented on hotels.html
> +<div class="hotels-cards">
Можно без дива. Список будет блочным, див тоже блочный, так что див можно убрать.

2023-01-27 06:53 UTC, summertime-fms commented on hotels.html
> +  </form>
Вот это можно в секцию выделить.

2023-01-27 06:53 UTC, summertime-fms commented on hotels.html
> +<footer class="page-footer">
Футер это все еще часть бади. Закрывается футер, затем закрывается бади, затем закрывается html

2023-01-27 06:53 UTC, summertime-fms commented on hotels.html
> +  <section class="footer-contacts-phone">
Секция - это когда внутри много контента по одной теме. Здесь внутри одна ссылка и я бы не стал выделять это в секцию. Как и ниже с копирайтом.. Можно просто оставить ссылками.

2023-01-27 06:53 UTC, summertime-fms commented on hotels.html
> +  <section class="footer-contacts-phone">
Как и выше тоже, брать в секцию один заголовок не лучшая идея. Ты можешь оставить просто заголовок)

2023-01-27 06:53 UTC, summertime-fms commented on index.html
> +<img src="" alt="Горы">
А давай вместо двух img сделаем один. В фигме просто сгруппируем картинки и экспортнем как одну.

2023-01-27 06:53 UTC, summertime-fms commented on index.html
> +  <section class="advantages">
Я бы поднял эту секцию повыше, чтобы h2 и p в нее входили.

2023-01-27 06:53 UTC, summertime-fms commented on index.html
> +      </li>
А где разметка блоков прямоугольных с изображением?

2023-01-27 06:53 UTC, summertime-fms commented on index.html
> +      <h2 class="main-header">
Выделим в секцию? Тут прослеживается отдельный блок бронирования.

2023-01-27 06:53 UTC, summertime-fms commented on index.html
> +        <h2 class="main-header">
Аналогично как и в каталоге, тоже в секцию можно убрать. Вообще легко понять секция или нет по заголовку. Если блоку можно дать заголовок то это секция. Внутри каждой секции должен быть h2.

2023-01-27 17:27 UTC, soulmonova commented on hotels.html
> +    <li class="navigation item">
Исправила

2023-01-28 13:27 UTC, soulmonova commented on hotels.html
> +  <main class="main-inner"
В скринкастах академии задают класс мейнам, хотя меня это тоже смутило...

2023-01-28 13:33 UTC, merged